# Generated by Django 4.2.4 on 2023-08-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationUser',
        ),
    ]
